/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MembershipManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CLAIM_MANAGER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "HOSPITAL_ROLE"
      | "PAYMENT_GRACE_PERIOD"
      | "adminTreasury"
      | "approveHealthcareProvider"
      | "changeTier"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "healthRiskPool"
      | "healthcareProviders"
      | "isActiveParticipant"
      | "isApprovedProvider"
      | "monthlyFee"
      | "participants"
      | "payMonthlyFee"
      | "registerHealthcareProvider"
      | "registerParticipant"
      | "rejectHealthcareProvider"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updateMembershipStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HealthcareProviderApproved"
      | "HealthcareProviderRegistered"
      | "HealthcareProviderRejected"
      | "MembershipPaid"
      | "MembershipStatusUpdated"
      | "ParticipantRegistered"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CLAIM_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HOSPITAL_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAYMENT_GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveHealthcareProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "healthRiskPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "healthcareProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveParticipant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payMonthlyFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerHealthcareProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerParticipant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectHealthcareProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMembershipStatus",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CLAIM_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HOSPITAL_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAYMENT_GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveHealthcareProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthRiskPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "healthcareProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "monthlyFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payMonthlyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerHealthcareProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectHealthcareProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMembershipStatus",
    data: BytesLike
  ): Result;
}

export namespace HealthcareProviderApprovedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthcareProviderRegisteredEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthcareProviderRejectedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembershipPaidEvent {
  export type InputTuple = [
    participant: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [participant: string, tier: bigint, amount: bigint];
  export interface OutputObject {
    participant: string;
    tier: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembershipStatusUpdatedEvent {
  export type InputTuple = [participant: AddressLike, isActive: boolean];
  export type OutputTuple = [participant: string, isActive: boolean];
  export interface OutputObject {
    participant: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantRegisteredEvent {
  export type InputTuple = [participant: AddressLike, tier: BigNumberish];
  export type OutputTuple = [participant: string, tier: bigint];
  export interface OutputObject {
    participant: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MembershipManager extends BaseContract {
  connect(runner?: ContractRunner | null): MembershipManager;
  waitForDeployment(): Promise<this>;

  interface: MembershipManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CLAIM_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  HOSPITAL_ROLE: TypedContractMethod<[], [string], "view">;

  PAYMENT_GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  adminTreasury: TypedContractMethod<[], [string], "view">;

  approveHealthcareProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  changeTier: TypedContractMethod<[newTier: BigNumberish], [void], "payable">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  healthRiskPool: TypedContractMethod<[], [string], "view">;

  healthcareProviders: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { status: bigint; isRegistered: boolean }],
    "view"
  >;

  isActiveParticipant: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  isApprovedProvider: TypedContractMethod<
    [provider: AddressLike],
    [boolean],
    "view"
  >;

  monthlyFee: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  participants: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, bigint] & {
        tier: bigint;
        isActive: boolean;
        lastPaymentTimestamp: bigint;
      }
    ],
    "view"
  >;

  payMonthlyFee: TypedContractMethod<[], [void], "payable">;

  registerHealthcareProvider: TypedContractMethod<[], [void], "nonpayable">;

  registerParticipant: TypedContractMethod<
    [tier: BigNumberish],
    [void],
    "payable"
  >;

  rejectHealthcareProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateMembershipStatus: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CLAIM_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "HOSPITAL_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAYMENT_GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveHealthcareProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeTier"
  ): TypedContractMethod<[newTier: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "healthRiskPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "healthcareProviders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { status: bigint; isRegistered: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveParticipant"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isApprovedProvider"
  ): TypedContractMethod<[provider: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "monthlyFee"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, bigint] & {
        tier: bigint;
        isActive: boolean;
        lastPaymentTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "payMonthlyFee"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "registerHealthcareProvider"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerParticipant"
  ): TypedContractMethod<[tier: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "rejectHealthcareProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateMembershipStatus"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "HealthcareProviderApproved"
  ): TypedContractEvent<
    HealthcareProviderApprovedEvent.InputTuple,
    HealthcareProviderApprovedEvent.OutputTuple,
    HealthcareProviderApprovedEvent.OutputObject
  >;
  getEvent(
    key: "HealthcareProviderRegistered"
  ): TypedContractEvent<
    HealthcareProviderRegisteredEvent.InputTuple,
    HealthcareProviderRegisteredEvent.OutputTuple,
    HealthcareProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "HealthcareProviderRejected"
  ): TypedContractEvent<
    HealthcareProviderRejectedEvent.InputTuple,
    HealthcareProviderRejectedEvent.OutputTuple,
    HealthcareProviderRejectedEvent.OutputObject
  >;
  getEvent(
    key: "MembershipPaid"
  ): TypedContractEvent<
    MembershipPaidEvent.InputTuple,
    MembershipPaidEvent.OutputTuple,
    MembershipPaidEvent.OutputObject
  >;
  getEvent(
    key: "MembershipStatusUpdated"
  ): TypedContractEvent<
    MembershipStatusUpdatedEvent.InputTuple,
    MembershipStatusUpdatedEvent.OutputTuple,
    MembershipStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantRegistered"
  ): TypedContractEvent<
    ParticipantRegisteredEvent.InputTuple,
    ParticipantRegisteredEvent.OutputTuple,
    ParticipantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "HealthcareProviderApproved(address)": TypedContractEvent<
      HealthcareProviderApprovedEvent.InputTuple,
      HealthcareProviderApprovedEvent.OutputTuple,
      HealthcareProviderApprovedEvent.OutputObject
    >;
    HealthcareProviderApproved: TypedContractEvent<
      HealthcareProviderApprovedEvent.InputTuple,
      HealthcareProviderApprovedEvent.OutputTuple,
      HealthcareProviderApprovedEvent.OutputObject
    >;

    "HealthcareProviderRegistered(address)": TypedContractEvent<
      HealthcareProviderRegisteredEvent.InputTuple,
      HealthcareProviderRegisteredEvent.OutputTuple,
      HealthcareProviderRegisteredEvent.OutputObject
    >;
    HealthcareProviderRegistered: TypedContractEvent<
      HealthcareProviderRegisteredEvent.InputTuple,
      HealthcareProviderRegisteredEvent.OutputTuple,
      HealthcareProviderRegisteredEvent.OutputObject
    >;

    "HealthcareProviderRejected(address)": TypedContractEvent<
      HealthcareProviderRejectedEvent.InputTuple,
      HealthcareProviderRejectedEvent.OutputTuple,
      HealthcareProviderRejectedEvent.OutputObject
    >;
    HealthcareProviderRejected: TypedContractEvent<
      HealthcareProviderRejectedEvent.InputTuple,
      HealthcareProviderRejectedEvent.OutputTuple,
      HealthcareProviderRejectedEvent.OutputObject
    >;

    "MembershipPaid(address,uint8,uint256)": TypedContractEvent<
      MembershipPaidEvent.InputTuple,
      MembershipPaidEvent.OutputTuple,
      MembershipPaidEvent.OutputObject
    >;
    MembershipPaid: TypedContractEvent<
      MembershipPaidEvent.InputTuple,
      MembershipPaidEvent.OutputTuple,
      MembershipPaidEvent.OutputObject
    >;

    "MembershipStatusUpdated(address,bool)": TypedContractEvent<
      MembershipStatusUpdatedEvent.InputTuple,
      MembershipStatusUpdatedEvent.OutputTuple,
      MembershipStatusUpdatedEvent.OutputObject
    >;
    MembershipStatusUpdated: TypedContractEvent<
      MembershipStatusUpdatedEvent.InputTuple,
      MembershipStatusUpdatedEvent.OutputTuple,
      MembershipStatusUpdatedEvent.OutputObject
    >;

    "ParticipantRegistered(address,uint8)": TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;
    ParticipantRegistered: TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
